"""LLM Wiki (Layer 2) file I/O + Layer 3 guide access (M5).

The wiki is fully rebuildable from the SQLite archive (Layer 1): pages live as
markdown under `wiki_dir` (`people/`, `topics/`), with an append-only `log.md`
journal and an auto-generated `index.md`. The nightly digest maintains pages
via the read/write methods here; the query agent reads them back.

`index.md` is generated by code (not hand-edited by the LLM) from each page's
first line, so the catalogue stays deterministic and rebuildable. The digest
watermark is derived from the last dated heading in `log.md` — the wiki stays
self-describing, no extra table needed.
"""

from __future__ import annotations

import os
import re
from datetime import date
from pathlib import Path

# Pages the digest may write. Anything else is rejected (path-traversal guard).
PAGE_DIRS = ("people", "topics")
ROOT_FILES = ("index.md", "log.md")

_LOG_DATE_RE = re.compile(r"^## (\d{4}-\d{2}-\d{2})\s*$", re.MULTILINE)


class Wiki:
    def __init__(self, wiki_dir: Path, guide_path: Path | None = None):
        self.wiki_dir = Path(wiki_dir)
        self.guide_path = Path(guide_path) if guide_path else None
        self.wiki_dir.mkdir(parents=True, exist_ok=True)

    # --- path validation -----------------------------------------------------

    def _safe_path(self, rel_path: str) -> Path:
        """Resolve a wiki-relative path, rejecting traversal / unknown locations.

        Allowed: `index.md`, `log.md`, and `people/*.md` / `topics/*.md`.
        Raises ValueError on anything else (so the LLM can't escape the dir).
        """
        base = self.wiki_dir.resolve()
        target = (base / rel_path).resolve()
        if not target.is_relative_to(base):
            raise ValueError(f"path escapes wiki dir: {rel_path}")
        if target.suffix != ".md":
            raise ValueError(f"not a markdown page: {rel_path}")
        parts = target.relative_to(base).parts
        if len(parts) == 1 and parts[0] in ROOT_FILES:
            return target
        if len(parts) == 2 and parts[0] in PAGE_DIRS:
            return target
        raise ValueError(f"page must be index.md, log.md or {PAGE_DIRS}/<name>.md: {rel_path}")

    # --- pages ---------------------------------------------------------------

    def read_page(self, rel_path: str) -> str | None:
        path = self._safe_path(rel_path)
        if not path.exists():
            return None
        return path.read_text(encoding="utf-8")

    def write_page(self, rel_path: str, content: str) -> None:
        """Atomically write a page (temp + os.replace) so a crash never leaves
        a half-written page that the next digest would read back."""
        path = self._safe_path(rel_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_suffix(path.suffix + ".tmp")
        tmp.write_text(content if content.endswith("\n") else content + "\n", encoding="utf-8")
        os.replace(tmp, path)

    def list_pages(self) -> list[str]:
        """Wiki-relative paths of all people/ and topics/ pages, sorted."""
        pages: list[str] = []
        for sub in PAGE_DIRS:
            d = self.wiki_dir / sub
            if d.is_dir():
                pages.extend(f"{sub}/{p.name}" for p in d.glob("*.md"))
        return sorted(pages)

    @staticmethod
    def _summary(content: str) -> str:
        """First non-empty line, stripped of leading markdown heading marks."""
        for line in content.splitlines():
            line = line.strip()
            if line:
                return line.lstrip("#").strip()
        return ""

    # --- index (auto-generated) ---------------------------------------------

    def render_index(self) -> str:
        """Build index.md content from the pages currently on disk."""
        by_dir: dict[str, list[str]] = {sub: [] for sub in PAGE_DIRS}
        for rel in self.list_pages():
            sub = rel.split("/", 1)[0]
            summary = self._summary(self.read_page(rel) or "")
            by_dir[sub].append(f"- {rel} — {summary}" if summary else f"- {rel}")
        headings = {"people": "## Люди", "topics": "## Темы"}
        lines = ["# Индекс вики", "", "Журнал: log.md", ""]
        for sub in PAGE_DIRS:
            lines.append(headings[sub])
            lines.extend(by_dir[sub] or ["(пусто)"])
            lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    def regenerate_index(self) -> str:
        content = self.render_index()
        self._safe_path("index.md").write_text(content, encoding="utf-8")
        return content

    def read_index(self) -> str:
        path = self._safe_path("index.md")
        return path.read_text(encoding="utf-8") if path.exists() else self.render_index()

    # --- log (append-only journal) ------------------------------------------

    def append_log(self, day: date, body: str) -> None:
        path = self._safe_path("log.md")
        header = "# Журнал\n\n" if not path.exists() else ""
        entry = f"## {day.isoformat()}\n\n{body.strip()}\n\n"
        with path.open("a", encoding="utf-8") as fh:
            fh.write(header + entry)

    def last_digested_date(self) -> date | None:
        """Watermark: the latest dated heading in log.md, or None if empty."""
        path = self._safe_path("log.md")
        if not path.exists():
            return None
        dates = _LOG_DATE_RE.findall(path.read_text(encoding="utf-8"))
        return max((date.fromisoformat(d) for d in dates), default=None)

    # --- guide (Layer 3) -----------------------------------------------------

    def guide(self) -> str:
        if self.guide_path and self.guide_path.exists():
            return self.guide_path.read_text(encoding="utf-8")
        return ""

    # --- rebuild -------------------------------------------------------------

    def reset(self) -> None:
        """Wipe Layer 2 (pages, index, log) for a deterministic --rebuild.
        Layer 3 (the guide) lives outside wiki_dir and is untouched."""
        import shutil

        if self.wiki_dir.exists():
            shutil.rmtree(self.wiki_dir)
        self.wiki_dir.mkdir(parents=True, exist_ok=True)
